name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  mongo_dart: ^0.9.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  dotenv: ^4.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
